- name: Install Postgres (with workaround for DP7)
  homebrew: name=postgres state=present install_options=no-perl
- name: Link Postgres LaunchAgent
  file: src=/usr/local/opt/postgresql/homebrew.mxcl.postgresql.plist dest=~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist state=link
- name: Start Postgres
  shell: launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
- name: Install MariaDB
  homebrew: name=mariadb state=present
- name: Install Redis
  homebrew: name=redis state=present
