- name: Install Postgres (with workaround for DP7)
  homebrew: name=postgres state=present install_options=no-perl
- name: Start Postgres
  shell: brew services start postgresql
- name: create the default postgres user
  shell: createuser -s {{ ansible_user_id }}
  ignore_errors: yes
- name: Create the default postgresql database
  shell: createdb -O {{ ansible_user_id }} {{ ansible_user_id }}
  ignore_errors: yes
- name: Install MariaDB
  homebrew: name=mariadb state=present
- name: Start mariadb
  shell: brew services start mariadb
- name: Install Redis
  homebrew: name=redis state=present
