---
# Everything related to ruby
- name: Install rbenv
  homebrew: name=rbenv state=present
- name: Install ruby-build
  homebrew: name=ruby-build state=present
- name: create the install location for rubies
  shell: mkdir -p ~/.rbenv/versions
- include: ruby-install.yml rubies={{ rubies }}
  vars:
    rubies:
      - {flavor: "ruby", version: "2.0.0-p645"}
      - {flavor: "ruby", version: "2.1.6"}
      - {flavor: "ruby", version: "2.2.2"}
      - {flavor: "ruby", version: "1.9.3-p551"}
